repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
    -   id: setup-cfg-fmt
